[connections.xai_db_conn]
url = "postgresql://neondb_owner:npg_W0mzqBwMPVZ6@ep-patient-block-a88vmqs8-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require"
pool_pre_ping = true
pool_recycle = 300
pool_timeout = 30



[api_keys]
cohere_api_key = "zt5s4tKna1ALgf0xVKwFLHEqDRJ0ezoscAk4WPAc"

[admin_user]
admin_user = "admin@uncg.edu"